/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:276d5320-7e8c-4026-961b-5b1f3550cea6",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_2CRYJCaWO",
    "aws_user_pools_web_client_id": "7eepq6dsjqa59ppjgmjab868tj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6zqc37ra3jgzdnfhlkt5t6teaq.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "null",
};

export default awsmobile;
